### ISSUE TITLE
Explore ways to financially support the collective and research on the platform

### ISSUE THREAD

**Issue by qwertyone** [crowdresearch/collective#38]
## Problem
Time, effort, and compensation are major concerns for the more experienced members of the group. Eventually, former leaders move on from CRG to other endeavors leading to an attrition that affects directly the elected roles found within the group.

## Proposal
This proposal is recruit 2 to 3 people to identify grants that can support members from other institutions to continue or raise their participation with the group and then secure the related grants with full effort.

## Short Term Implications  
A team of researchers from the collective identify between 5 to 7 grants of greater than $10,000 to target for application.

## Long Term Implications
A more varied and diverse research group of leaders who can capably support the collective's members and increase the organizational capacity of the group.

### aside
I do not seek to complete this task for my own personal benefit.

**Comment by mbernst** [comment]
I fully support this goal. I think a few things need to be worked out 'ere we can achieve clear consensus on a plan. Please bear with me on some minutae that unfortunately really matter here, since I've learned them through hard experience.

Grants are complicated. Because I have been a collaborator on this project, Stanford has thus far provided support for the grant submissions representing many hours of help and very technical expertise, including:
- Compliance review
- Auditing
- Financial budget management
- Aid with data management plans
- Aid with facilities plans
- Institutional Review Board (ethics review)

There are implications of this. First, it requires a Stanford PI to be named on the grant (thus far, me), and it requires that Stanford receive and disburse the funds. All universities charge overhead for this, depending on whether it's a federal grant (e.g., NSF), internal grant (e.g., Hasso) or gift funds (e.g., from a company).

When we apply for grants without Stanford affiliation, it requires a formal organization set up to receive the grant funds and expertise to fill the roles I listed above. I think this question of an outside organization is a very complicated issue, one I'm happy to pursue, but it has been something that in the past our "trigger" mechanism stated we would wait until we have a bit more volume to fully understand.

How should we proceed? Maintain the existing setup, but add a group working on the grant seeking? Or should we make a broader change somehow? And if we make the broader change, how does the group decide how to spend any funds it receives?

**Comment by qwertyone** [comment]
- Target of $10,000.

@mbernst This has consensus. I need to ask, is the $10,000 target meaningful for the funding process through the University? or is it too low practically?

@shirishgoyal @neilthemathguy @markwhiting How does the target look for you? I am not asking people residing in India since the cost of living difference is huge and I think you three are in areas with higher than average costs of living in the USA. I think your responses will easily address their concerns.

**Comment by qwertyone** [comment]
- logistical issues

@mbernst I am more likely to fall back on what is familiar. Keep the existing setup unless another person ... might be willing to handle it through their institution. I am a single individual and believe that the logistical operations are not in my ability to handle.

If @iceLearn is able and wants she might inform the Sri Lanka side of the discussion.

**Comment by qwertyone** [comment]
## Nominations for the grant search and selection committee

This proposal is aimed for self motivation and an opportunity to support members of the group. It was agreed that 2 to 3 people would be involved in the search, which might be heavily influenced by this small group.

The consensus is:
>  recruit 2 to 3 people to identify grants that can support members from other institutions to continue or raise their participation with the group and then secure the related grants with full effort.

If you have a burning question or know of a researcher in the group with a worthwhile project to pursue, add details and nominate. Self nomination is strongly encouraged for this. If you know of another institutional link that might benefit this group in an alliance research project, please nominate yourself as well.

**Comment by qwertyone** [comment]
## Self nomination
@anotherhuman is willing to play a lead role to assist in the targeting phase of this proposal as well as other later steps. He will not be in a role to develop the content or ideas that will direct and guide the search.

**Comment by shirishgoyal** [comment]
@qwertyone What will this fund cover? Who all will it be disbursed to? How many people will it support?
I cannot answer your question unless I know how you came up with this arbitrary number.

**Comment by qwertyone** [comment]
I was aiming to get the conversation started. This is not my expertise. I suspect it might be low, but than again, I would rather think that the process should be driven by the research questions and their needs. @shirishgoyal Below is from the Knight Foundation from one of its programs.
![image](https://user-images.githubusercontent.com/6076358/34698235-5652ba50-f4d7-11e7-96af-832e5fa88054.png)

**Comment by iceLearn** [comment]
As I understand @qwertyone high level objective is to form a group who will be exploring grants to this project. As @mbernst mentioned some of the grants will need more support, but this group should be able to work with the PI and also this group can look for new grants such as from Mozilla other independent funds.

**Comment by qwertyone** [comment]
The proposal has a condition for a group to 2 to 3. If by the end of next Monday 1/15, no others express interest by nomination, this proposal will be closed and a new proposal will have be submitted through the constitutional process. 18 days have passed since this proposal was written and achieved consensus.
